--INVENTORY TABLES
DELETE FROM STOCK;
DELETE FROM STOCK_HISTORY;
DELETE FROM STOCK_BATCH;
DELETE FROM VENDOR;

--ORDER TABLES
DELETE FROM LINE_ITEM;
DELETE FROM INVOICE;
DELETE FROM  BUYER;
DELETE FROM  ITEM;

--DOMAIN TABLES
DELETE FROM  CATEGORY;
DELETE FROM  SUBCATEGORY;
DELETE FROM  BRAND;
DELETE FROM  MODEL;

DELETE FROM  TAX;
DELETE FROM  USERS;
DELETE FROM  TRADER;
DELETE FROM  ADDRESS;

--SEQUENCES will be dropped when the referred column is dropped