--INVENTORY TABLES
DROP TABLE STOCK;
DROP TABLE STOCK_HISTORY;
DROP TABLE STOCK_BATCH;
DROP TABLE VENDOR;


--ORDER TABLES
DROP TABLE LINE_ITEM;
DROP TABLE INVOICE;
DROP TABLE ITEM;
DROP TABLE TAX;
DROP TABLE STORE;


--ENUM TYPES
DROP TYPE CATEGORY;
DROP TYPE SUB_CATEGORY;
DROP TYPE BRAND;
DROP TYPE SIZE;
