--INVENTORY TABLES
DELETE FROM STOCK;
DELETE FROM STOCK_HISTORY;
DELETE FROM STOCK_BATCH;
DELETE FROM VENDOR;


--ORDER TABLES
DELETE FROM LINE_ITEM;
DELETE FROM INVOICE;
DELETE FROM ITEM;
DELETE FROM TAX;
DELETE FROM STORE;
