
-- Disable DB objects

-- Disabling triggers for functional tests to create records with various dates

--ALTER TABLE STORE DISABLE TRIGGER STORE_BIT;

--ALTER TABLE TAX DISABLE TRIGGER TAX_BIT;

--ALTER TABLE ITEM DISABLE TRIGGER ITEM_BIT;


ALTER TABLE INVOICE DISABLE TRIGGER INVOICE_BIT;

ALTER TABLE LINE_ITEM DISABLE TRIGGER LINE_ITEM_BIT;


--ALTER TABLE STOCK DISABLE TRIGGER STOCK_BIT


--ALTER TABLE VENDOR DISABLE TRIGGER VENDOR_BIT;

--ALTER TABLE STOCK_BATCH DISABLE TRIGGER STOCK_BATCH_BIT

--ALTER TABLE STOCK_HISTORY DISABLE TRIGGER STOCK_HISTORY_BIT;