
-- Enable DB objects

-- Enabling triggers

--ALTER TABLE STORE ENABLE TRIGGER STORE_BIT;

--ALTER TABLE TAX ENABLE TRIGGER TAX_BIT;

--ALTER TABLE ITEM ENABLE TRIGGER ITEM_BIT;


ALTER TABLE INVOICE ENABLE TRIGGER INVOICE_BIT;

ALTER TABLE LINE_ITEM ENABLE TRIGGER LINE_ITEM_BIT


--ALTER TABLE STOCK ENABLE TRIGGER STOCK_BIT


--ALTER TABLE VENDOR ENABLE TRIGGER VENDOR_BIT;

--ALTER TABLE STOCK_BATCH ENABLE TRIGGER STOCK_BATCH_BIT

--ALTER TABLE STOCK_HISTORY ENABLE TRIGGER STOCK_HISTORY_BIT;