SELECT enum_range(NULL::type)

SELECT * FROM STORE;

select * from tax;

select * from line_item;

SELECT * FROM INVOICE;

INSERT INTO INVOICE(ID, STORE_ID, TOTAL_TAX, TOTAL_PRICE, ACTIVE, CREATED_USER, MODIFIED_USER)
VALUES (1004, 1012, 10.20, 21.90, TRUE, 'APP-SERVICES', 'APP-SERVICES');
COMMIT;

ALTER TABLE INVOICE DISABLE TRIGGER INVOICE_BIT;
ALTER TABLE INVOICE ENABLE TRIGGER INVOICE_BIT;

DELETE FROM VENDOR;

SELECT * FROM ITEM;

SELECT * FROM VENDOR;

SELECT * FROM STOCK where item_id=1117;

SELECT * FROM STOCK_BATCH;

SELECT * FROM STOCK_HISTORY;

SELECT * FROM LINE_ITEM where invoice_id = 1005;

SELECT * FROM INVOICE;

SELECT * FROM STORE;


SELECT LI.QUANTITY, T.CGST, T.SGST, LI.TOTAL_TAX, LI.TOTAL_PRICE, ((LI.QUANTITY*T.CGST) + (LI.QUANTITY*T.SGST)), (LI.QUANTITY*I.PRICE) 
FROM LINE_ITEM LI, ITEM I, TAX T 
where LI.ITEM_ID = I.ID
AND I.TAX_ID = T.ID
AND LI.invoice_id = 1006;